// Code generated by MockGen. DO NOT EDIT.
// Source: sfn.go

// Package sfn is a generated GoMock package.
package sfn

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockState is a mock of State interface
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
}

// MockStateMockRecorder is the mock recorder for MockState
type MockStateMockRecorder struct {
	mock *MockState
}

// NewMockState creates a new mock instance
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// Run mocks base method
func (m *MockState) Run(arg0 []byte) ([]byte, error) {
	ret := m.ctrl.Call(m, "Run", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run
func (mr *MockStateMockRecorder) Run(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockState)(nil).Run), arg0)
}

// Next mocks base method
func (m *MockState) Next() string {
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(string)
	return ret0
}

// Next indicates an expected call of Next
func (mr *MockStateMockRecorder) Next() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockState)(nil).Next))
}

// IsEnd mocks base method
func (m *MockState) IsEnd() bool {
	ret := m.ctrl.Call(m, "IsEnd")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnd indicates an expected call of IsEnd
func (mr *MockStateMockRecorder) IsEnd() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnd", reflect.TypeOf((*MockState)(nil).IsEnd))
}

// MockStepFunction is a mock of StepFunction interface
type MockStepFunction struct {
	ctrl     *gomock.Controller
	recorder *MockStepFunctionMockRecorder
}

// MockStepFunctionMockRecorder is the mock recorder for MockStepFunction
type MockStepFunctionMockRecorder struct {
	mock *MockStepFunction
}

// NewMockStepFunction creates a new mock instance
func NewMockStepFunction(ctrl *gomock.Controller) *MockStepFunction {
	mock := &MockStepFunction{ctrl: ctrl}
	mock.recorder = &MockStepFunctionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStepFunction) EXPECT() *MockStepFunctionMockRecorder {
	return m.recorder
}

// StartExecution mocks base method
func (m *MockStepFunction) StartExecution(arg0 []byte) (ExecutionResult, error) {
	ret := m.ctrl.Call(m, "StartExecution", arg0)
	ret0, _ := ret[0].(ExecutionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartExecution indicates an expected call of StartExecution
func (mr *MockStepFunctionMockRecorder) StartExecution(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartExecution", reflect.TypeOf((*MockStepFunction)(nil).StartExecution), arg0)
}

// SetStateFactory mocks base method
func (m *MockStepFunction) SetStateFactory(arg0 StateFactory) {
	m.ctrl.Call(m, "SetStateFactory", arg0)
}

// SetStateFactory indicates an expected call of SetStateFactory
func (mr *MockStepFunctionMockRecorder) SetStateFactory(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStateFactory", reflect.TypeOf((*MockStepFunction)(nil).SetStateFactory), arg0)
}
